apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-helm
  # to enable auto-login:
  users.anonymous.enabled: 'true'

  # resource customization for a healthy ingress
  # https://github.com/argoproj/argo-cd/issues/1704#issuecomment-1516353335
  resource.customizations: |
      networking.k8s.io/Ingress:
        health.lua: |
          hs = {}
          hs.status = 'Healthy'
          return hs
