apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # an applicationsset should only create the applications not modify them 
  # (e.g. to enable that a user can disable the auto-synch)
  applicationsetcontroller.policy: 'create-only'
  
  # run server (ui) without TLS
  server.insecure: 'true'
  server.rootpath: '/argocd'