apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics-server
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: victoria-metrics-server
      annotations:
        fluentbit.io/parser: victoria-metrics
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-server
          image: victoriametrics/victoria-metrics:v1.101.0
          imagePullPolicy: IfNotPresent
          args:
            - --retentionPeriod=1  # 1 month
            - --storageDataPath=/storage
            - --promscrape.config=/config/scrape-config.yaml
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
            - --search.latencyOffset=0
            - --search.maxConcurrentRequests=5
            - --search.maxMemoryPerQuery=20MB
            - --memory.allowedBytes=200MB
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8428
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - containerPort: 8428
              name: http
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              memory: 400Mi
              cpu: 1000m
            requests:
              memory: 250Mi
              cpu: 10m
          volumeMounts:
            - mountPath: /storage
              name: data
            - mountPath: /config
              name: config
      serviceAccountName: victoria-metrics-server
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            name: victoria-metrics-server
          name: config
        - name: data
          persistentVolumeClaim:
            claimName: victoria-metrics-server
