apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics-server
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: http
  selector:
    app: victoria-metrics-server
  type: ClusterIP
