apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pvc-exporter
  template:
    metadata:
      labels:
        app: pvc-exporter
      annotations:
        fluentbit.io/parser: custom-go-exporter
    spec:
      serviceAccountName: pvc-exporter
      containers:
        - name: pvc-exporter
          image: schulzsystemtechnik/iiot-app-pvc-exporter:1.0.0
          imagePullPolicy: IfNotPresent
          args:
            - -log_level=debug
          resources:
            limits:
              memory: 40Mi
              cpu: 1000m
            requests:
              memory: 10Mi
              cpu: 2m
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/openebs/local
              name: openebs
              readOnly: True
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - hostPath:
            path: /var/openebs/local
          name: openebs