apiVersion: v1
kind: Service
metadata:
  name: pvc-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    app: pvc-exporter
