# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.2-85-ga15aa4a
_src_path: https://github.com/SchulzSystemtechnik/iiot-base-box.git
additional_system_apps:
- local_monitoring
advanced_mode: false
environment: testing
hardware_setup: []
name: test-pqraus-vm
preset_type: IIoT
repo_github_name: pQraus/iiot-project-test-pqraus-vm
teleport_usage_label: iiot
