teleport:
  auth_servers: ["prod.teleport.schulzdevcloud.com:443"]
  data_dir: "/teleport-agent/data"
  auth_token: "/teleport-agent/config/join-token"
  diag_addr: "localhost:7755"
  ca_pin:
    - sha256:1b03b275dd06af7eff4795f2c8cbb0d61a7c528852c51d0a461bb4be570fcd20
  log:
    severity: INFO
    output: stderr
    format:
      output: text
      extra_fields: ["timestamp","level","component","caller"]

kubernetes_service:
  enabled: true
  kubeconfig_file: "/secrets/kubernetes/admin/config"
  labels:
    env: dev
    usage: iiot
    
app_service:
  enabled: true
  apps:
    - name: talos-test-pqraus-vm
      uri: tcp://localhost:51002
      commands:
        - name: teleport-version
          command: ["/teleport-agent/bin/teleport", "version", "--raw"]
          period: 0h10m0s
        - name: teleport-sync-status
          command: ["/bin/busybox", "cat", "/teleport-agent/sync-status"]
          period: 0h10m0s
      labels:
        env: dev
        usage: iiot
        kind: talos
        base-repo-version: v2.3.2-124-gf05e8a5
        repo-url: https://github.com/pQraus/iiot-project-test-pqraus-vm
        local-monitoring: True
        remote-monitoring: False

    - name: private-test-pqraus-vm
      uri: http://10.96.0.100:80
      labels:
        env: dev
        usage: iiot
        kind: ingress-private

db_service:
  enabled: false

auth_service:
  enabled: false
ssh_service:
  enabled: false
proxy_service:
  enabled: false