apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: openebs
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local"
    openebs.io/cas-type: local
    storageclass.kubernetes.io/is-default-class: "true"
  name: openebs-hostpath
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: localpv-provisioner
    chart: localpv-provisioner-4.1.0
    component: localpv-provisioner
    heritage: Helm
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 4.1.0
    release: openebs
  name: openebs-localpv-provisioner
  namespace: openebs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-2"
  labels:
    app.kubernetes.io/instance: openebs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: openebs-4.1.0
  name: openebs-pre-upgrade-hook
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: localpv-provisioner
    chart: localpv-provisioner-4.1.0
    component: localpv-provisioner
    heritage: Helm
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 4.1.0
    release: openebs
  name: openebs-localpv-provisioner
rules:
- apiGroups:
  - '*'
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - namespaces
  - pods
  - events
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - resourcequotas
  - limitranges
  verbs:
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - storageclasses
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
- apiGroups:
  - openebs.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-2"
  labels:
    app.kubernetes.io/instance: openebs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: openebs-4.1.0
  name: openebs-pre-upgrade-hook
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - delete
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: localpv-provisioner
    chart: localpv-provisioner-4.1.0
    component: localpv-provisioner
    heritage: Helm
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 4.1.0
    release: openebs
  name: openebs-localpv-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openebs-localpv-provisioner
subjects:
- kind: ServiceAccount
  name: openebs-localpv-provisioner
  namespace: openebs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    app.kubernetes.io/instance: openebs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: openebs-4.1.0
  name: openebs-pre-upgrade-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openebs-pre-upgrade-hook
subjects:
- kind: ServiceAccount
  name: openebs-pre-upgrade-hook
  namespace: openebs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: localpv-provisioner
    chart: localpv-provisioner-4.1.0
    component: localpv-provisioner
    heritage: Helm
    openebs.io/component-name: openebs-localpv-provisioner
    openebs.io/version: 4.1.0
    release: openebs
  name: openebs-localpv-provisioner
  namespace: openebs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localpv-provisioner
      component: localpv-provisioner
      release: openebs
  strategy:
    rollingUpdate: null
    type: Recreate
  template:
    metadata:
      annotations:
        fluentbit.io/parser: openebs
      labels:
        app: localpv-provisioner
        chart: localpv-provisioner-4.1.0
        component: localpv-provisioner
        heritage: Helm
        name: openebs-localpv-provisioner
        openebs.io/component-name: openebs-localpv-provisioner
        openebs.io/version: 4.1.0
        release: openebs
    spec:
      containers:
      - env:
        - name: OPENEBS_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENEBS_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: OPENEBS_IO_ENABLE_ANALYTICS
          value: "false"
        - name: OPENEBS_IO_BASE_PATH
          value: /var/openebs/local
        - name: OPENEBS_IO_HELPER_IMAGE
          value: openebs/linux-utils:4.1.0
        - name: OPENEBS_IO_INSTALLER_TYPE
          value: localpv-charts-helm
        - name: LEADER_ELECTION_ENABLED
          value: "true"
        image: openebs/provisioner-localpv:4.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - test `pgrep -c "^provisioner-loc.*"` = 1
          initialDelaySeconds: 30
          periodSeconds: 60
        name: openebs-localpv-provisioner
        resources: null
      securityContext: {}
      serviceAccountName: openebs-localpv-provisioner
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "0"
  labels:
    app.kubernetes.io/instance: openebs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: openebs-4.1.0
  name: openebs-pre-upgrade-hook
  namespace: openebs
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: openebs
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: openebs-4.1.0
      name: openebs-pre-upgrade-hook
    spec:
      containers:
      - args:
        - (kubectl annotate --overwrite crd volumesnapshots.snapshot.storage.k8s.io
          volumesnapshotclasses.snapshot.storage.k8s.io volumesnapshotcontents.snapshot.storage.k8s.io
          helm.sh/resource-policy=keep || true) && (kubectl -n openebs delete deploy
          -l openebs.io/component-name=openebs-localpv-provisioner --ignore-not-found)
        command:
        - /bin/sh
        - -c
        image: docker.io/bitnami/kubectl:1.25.15
        imagePullPolicy: IfNotPresent
        name: pre-upgrade-job
      restartPolicy: Never
      serviceAccountName: openebs-pre-upgrade-hook
