apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

resources:
  - resources/openebs-namespace.yaml

helmCharts:
  - name: openebs
    version: 3.10.0
    repo: https://openebs.github.io/charts
    releaseName: openebs
    includeCRDs: true
    namespace: openebs
    valuesInline:  # see defaults: https://github.com/openebs/charts/blob/openebs-3.10.0/charts/openebs/values.yaml
      ndm:
        enabled: false
      ndmOperator:
        enabled: false
      localprovisioner:
        deviceClass:
          enabled: false  # disable localpv-device (it's not needed on a device with a disk for os+data)
        hostpathClass:
          reclaimPolicy: Retain  # retain the pv after the corresponding pvc is deleted
          isDefaultClass: true
