apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openebs

resources:
  - resources/openebs-namespace.yaml

helmCharts:
  - name: openebs
    version: 4.1.0
    repo: https://openebs.github.io/openebs
    releaseName: openebs
    namespace: openebs
    valuesInline:  # see defaults: https://github.com/openebs/openebs/blob/v4.1.0/charts/values.yaml
      openebs-crds:
        csi:
          volumeSnapshots:
            enabled: false
            keep: false

      localpv-provisioner: # see https://github.com/openebs/dynamic-localpv-provisioner/blob/v4.1.0/deploy/helm/charts/values.yaml
        analytics:
          enabled: false # disable sending analytics to google domain
        hostpathClass:
          reclaimPolicy: Retain  # retain the pv after the corresponding pvc is deleted
          isDefaultClass: true

      zfs-localpv:
        enabled: false
      lvm-localpv:
        enabled: false
      mayastor:
        enabled: false

      engines:
        local:
          lvm:
            enabled: false
          zfs:
            enabled: false
        replicated:
          mayastor:
            enabled: false

patches:
  - path: patches/container-patches.yaml
    target:
      kind: Deployment
