apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: process-exporter
  template:
    metadata:
      labels:
        app: process-exporter
      annotations:
        fluentbit.io/parser: custom-go-exporter
    spec:
      containers:
        - name: process-exporter
          image: schulzsystemtechnik/iiot-app-process-exporter:1.1.0
          resources:
            limits:
              memory: 40Mi
              cpu: 1000m
            requests:
              memory: 10Mi
              cpu: 2m
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: proc
              mountPath: /proc
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
