apiVersion: v1
kind: Service
metadata:
  name: process-exporter
  namespace: monitoring
spec:
  selector:
    app: process-exporter
  ports:
    - port: 9001
      targetPort: 8080
      protocol: TCP
      name: metrics
