apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - private
  routes:
  - match: PathPrefix(`/argocd`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-argocd-prefix
  namespace: argocd
spec:
  addPrefix:
    prefix: /argocd
---
# default route
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-default
  namespace: argocd
spec:
  entryPoints:
    - private
  routes:
  - match: Path(`/`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
    middlewares:
    - name: add-argocd-prefix
