namespace: teleport-configurator

configMapGenerator:
  - name: teleport-config
    files:
      - config/config.yaml
    options:
      disableNameSuffixHash: true

images:
  - name: schulzsystemtechnik/iiot-misc-teleport-configurator
    newTag: stable

resources:
  - resources/configurator-cronjob.yaml
  - resources/configurator-namespace.yaml
  - resources/configurator-post-sync-job.yaml
