apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
      annotations:
        fluentbit.io/parser: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: schulzsystemtechnik/iiot-app-fluent-bit:2.2.3-1.0
          imagePullPolicy: IfNotPresent
          args:
            - --workdir=/fluent-bit/etc
            - --config=/fluent-bit/etc/conf/fluent-bit.conf
          ports:
            - containerPort: 2020
              name: http
              protocol: TCP
            - containerPort: 5000
              name: talos-services
              protocol: TCP
            - containerPort: 6000
              name: talos-kernel
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          resources:
            limits:
              memory: 40Mi
              cpu: 200m
            requests:
              memory: 10Mi
              cpu: 50m
          volumeMounts:
            - mountPath: /fluent-bit/etc/conf
              name: config
            - mountPath: /var/log/
              name: varlog
            - mountPath: /etc/machine-id
              name: etcmachineid
              readOnly: true
      dnsPolicy: ClusterFirst
      serviceAccountName: fluent-bit
      volumes:
        - configMap:
            name: fluent-bit
          name: config
        - hostPath:
            path: /var/log/
          name: varlog
        - hostPath:
            path: /etc/machine-id
            type: File
          name: etcmachineid
