apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 2020
      protocol: TCP
      targetPort: http
  selector:
    app: fluent-bit
  type: ClusterIP
