apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/sealed-secrets-namespace.yaml

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.14.1
    valuesInline:
      namespace: sealed-secrets
      fullnameOverride: sealed-secrets-controller
    includeCRDs: true
