{
 "title": "Logs Insights",
 "tags": [
  "iiot",
  "div"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   },
   { "name": "line_filter", "label": "Line filter" },
   { "name": "extra_filter", "label": "Extra filter" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs (max 500 lines)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n|= \"$line_filter\"\r\n| json\r\n| line_format `- {{printf \"%-8.8s\" ._level}} - {{printf \"%-14.14s\" ._namespace}} - {{printf \"%-50.50s\" ._pod}} - {{if .template_parsed}}{{.template_parsed}}{{else if .log}}{{.log}}{{else if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs volume",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Additional statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [60s]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}