{
 "title": "Overview",
 "tags": [
  "iiot",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "current_unix_time", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Box Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{job=\"kube_state_metrics\", node!=\"\"} @ $current_unix_time) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric provider status",
   "type": "stat",
   "description": "Red = Missing, Green = OK",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube_state_metrics\"} @ $current_unix_time)\nor\nabsent(up{job=\"kube_state_metrics\"} @ $current_unix_time) - 1",
     "legendFormat": "Kube-State-Metrics"
    },
    {
     "expr": "sum(up{job=\"cadvisor\"} @ $current_unix_time)\nor\nabsent(up{job=\"cadvisor\"} @ $current_unix_time) - 1",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "sum(up{job=\"node_exporter\"} @ $current_unix_time)\nor\nabsent(up{job=\"node_exporter\"} @ $current_unix_time) - 1",
     "legendFormat": "Node-Exporter"
    },
    {
     "expr": "sum(up{job=\"process_exporter\"} @ $current_unix_time)\nor\nabsent(up{job=\"process_exporter\"} @ $current_unix_time) - 1",
     "legendFormat": "Process-Exporter"
    },
    {
     "expr": "sum(up{job=\"aggregated_metric_exporter\"} @ $current_unix_time)\r\nor\r\nabsent(up{job=\"aggregated_metric_exporter\"} @ $current_unix_time) - 1",
     "legendFormat": "Aggregated-Metric-Exporter"
    },
    {
     "expr": "sum(up{job=\"kube_summary_exporter\"} @ $current_unix_time)\r\nor\r\nabsent(up{job=\"kube_summary_exporter\"} @ $current_unix_time) - 1",
     "legendFormat": "Kube-Summary-Exporter"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Failed\"} @ $current_unix_time)\r\n+\r\nsum(\r\n  kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Running\"} @ $current_unix_time\r\n  * on(uid)\r\n  kube_pod_status_ready{job=\"kube_state_metrics\", condition=\"false\"} @ $current_unix_time\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Pending\"} @ $current_unix_time)"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Running\"} @ $current_unix_time)\r\n-\r\nsum(\r\n  kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Running\"} @ $current_unix_time\r\n  * on(uid)\r\n  kube_pod_status_ready{job=\"kube_state_metrics\", condition=\"false\"} @ $current_unix_time\r\n)"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Succeeded\"} @ $current_unix_time)"
    },
    {
     "expr": "sum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Unknown\"} @ $current_unix_time)"
    }
   ]
  },
  { "title": "Resources", "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 } },
  {
   "title": "Versions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "box_info{job=\"aggregated_metric_exporter\"} @ $current_unix_time",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 13, "w": 12, "x": 12, "y": 10 } },
  { "title": "Div", "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 } },
  {
   "title": "IPv4",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_network_address_info{job=\"node_exporter\", address=~\"\\\\d+\\\\.\\\\d+\\\\.\\\\d+\\\\.\\\\d+\", scope=\"global\"}) by (device, address, netmask)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_network_address_info{job=\"node_exporter\", address!~\"\\\\d+\\\\.\\\\d+\\\\.\\\\d+\\\\.\\\\d+\"}) by (device, address, netmask, scope)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}