{
 "title": "Pod Logs",
 "tags": [
  "iiot",
  "div",
  "pod"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "columns",
    "label": "Columns",
    "query": "Level : level, Namespace : namespace, Pod : pod, None : none"
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   },
   {
    "name": "level",
    "label": "Level",
    "query": "critical, error, warning, info, debug, trace, unknown"
   },
   { "name": "line_filter", "label": "Line filter" },
   { "name": "extra_filter", "label": "Extra filter" }
  ]
 },
 "panels": [
  {
   "title": "How To",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "### Setting up your pods\nTo set up your pods, read [this](https://github.com/SchulzSystemtechnik/iiot-base-box/blob/v4.0.2-74-g573c6ef/docs/system-apps/monitoring/monitoring.md#manifest-configuration)\n\n### Filtering\nTo filter the logs according to your needs, use the filter at the top of the dashboard. First select your namespace, then your pod, and so on. If you are happy with your filters, use the time range to define, which exact logs you want to see. Keep in mind, that only the last 500 logs are shown. You can also use the diagrams or the graph to filter the logs."
     }
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Logs (max 1000 lines)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n|= \"$line_filter\"\r\n| json\r\n| line_format `{{if count \"$columns\" \"level\"}}- {{printf \"%-8.8s\" ._level}} {{end}}{{if count \"$columns\" \"namespace\"}}- {{printf \"%-14.14s\" ._namespace}} {{end}}{{if count \"$columns\" \"pod\"}}- {{printf \"%-50.50s\" ._pod}} {{end}}- {{if .template_parsed}}{{.template_parsed}}{{else if .log}}{{.log}}{{else if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Logs per level",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{_level}}"
    }
   ]
  },
  {
   "title": "Logs per pod",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 7, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_pod)",
     "legendFormat": "{{_pod}}"
    }
   ]
  },
  { "title": "Additional statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-pod-logs\", _namespace=~\"$namespace\", _pod=~\"$pod\", _container=~\"$container\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{_level}}"
    }
   ]
  }
 ]
}