{
 "title": "PVCs",
 "tags": [
  "iiot",
  "resources",
  "pvc"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pvc",
    "label": "PVC",
    "query": {
     "query": "label_values(persistentvolume_used_bytes{namespace=~\"$namespace\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "persistentvolume_used_bytes{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Persistent volume claims",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (persistentvolumeclaim_status{job=\"pvc_exporter\", namespace=~\"$namespace\"} == 1) by (name, namespace, status_phase, storageclass)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent volumes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (persistentvolume_capacity_bytes{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (name, namespace, persistentvolumeclaim, storageclass)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (persistentvolume_used_bytes{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (name, namespace)\r\n/\r\nsum (persistentvolume_capacity_bytes{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (name, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (persistentvolume_used_bytes{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"}) by (name, namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (persistentvolume_status{job=\"pvc_exporter\", namespace=~\"$namespace\", persistentvolumeclaim=~\"$pvc\"} == 1) by (name, namespace, status_phase)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}