{
 "title": "Resources (Pod)",
 "tags": [
  "iiot",
  "resources"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "average",
    "label": "Moving Average",
    "query": "None : 1s, 1m, 5m, 10m, 15m, 30m, 1h, 3h, 6h"
   },
   { "name": "current_unix_time", "query": { "query": "" } },
   {
    "name": "memory_type",
    "label": "Memory Type",
    "query": "Working Set : container_memory_working_set_bytes, RSS : container_memory_rss"
   }
  ]
 },
 "panels": [
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\"} @ $current_unix_time * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Owner Kind",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_owner{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\"} @ $current_unix_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_status_phase{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\"} @ $current_unix_time == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU cores by container",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[$__rate_interval])) by (container) * 1000\r\n    )[$average]\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory by container ($memory_type)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum({__name__=\"$memory_type\", job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}) by (container)\r\n    )[$average]\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"}[2m] @ $current_unix_time)) by (container) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", resource=\"cpu\"} @ $current_unix_time) by (container) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", resource=\"cpu\"} @ $current_unix_time) by (container) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", resource=\"memory\"} @ $current_unix_time) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", resource=\"memory\"} @ $current_unix_time) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_container_info{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_running{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time == 1) by (container)\r\nor\r\nsum(kube_pod_container_status_ready{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time == 1) by (container) + 1\r\nor\r\nsum(kube_pod_container_status_terminated{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time == 1) by (container) + 2\r\nor\r\nsum(kube_pod_container_status_waiting{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time == 1) by (container) + 3",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting_reason{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time) by (container, reason)\r\nor\r\nsum(kube_pod_container_status_terminated_reason{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time) by (container, reason)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\"} @ $current_unix_time) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-events\"}\r\n| json\r\n| metadata_namespace = \"$namespace\"\r\n| metadata_name =~ \"$pod.*\""
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs (limit 200)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-pod-logs\", _namespace=\"$namespace\", _pod=\"$pod\"}\r\n| json\r\n| line_format `- {{printf \"%-8.8s\" ._level}} - {{if .template_parsed}}{{.template_parsed}}{{else if .log}}{{.log}}{{else if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 200
    }
   ]
  },
  { "title": "Network usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Receive Bandwith (Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_receive_bytes_total{job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval])) by (pod)\r\n    )[$average]\r\n)",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Transmit Bandwith (Pod)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_transmit_bytes_total{job=\"cadvisor\", namespace=\"$namespace\", pod=\"$pod\"}[$__rate_interval])) by (pod)\r\n    )[$average]\r\n)",
     "legendFormat": "Value"
    }
   ]
  }
 ]
}