{
 "title": "Resources (Namespace)",
 "tags": [
  "iiot",
  "resources",
  "namespace"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "average",
    "label": "Moving Average",
    "query": "None : 1s, 1m, 5m, 10m, 15m, 30m, 1h, 3h, 6h"
   },
   { "name": "current_unix_time", "query": { "query": "" } },
   { "name": "pod_filter", "label": "Pod Filter" },
   {
    "name": "memory_type",
    "label": "Memory Type",
    "query": "Working Set : container_memory_working_set_bytes, RSS : container_memory_rss"
   }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU cores by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"}[$__rate_interval])) by (pod) * 1000\r\n    )[$average]\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory by pod ($memory_type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum({__name__=\"$memory_type\", job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"}) by (pod)\r\n    )[$average]\r\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"}[2m] @ ($current_unix_time))) by (pod) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_container_info{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"} @ $current_unix_time) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"} @ $current_unix_time) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_pod_status_phase{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"} @ $current_unix_time == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_ready{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"} @ $current_unix_time) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"} @ $current_unix_time) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "$current_unix_time\r\n-\r\nmax(kube_pod_created{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"}) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(last_over_time(kube_pod_container_state_started{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"}[30d])) by (pod)\r\n*\r\ncount(kube_pod_info{job=\"kube_state_metrics\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"}) by (pod)\r\n-\r\n$current_unix_time",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\", container!=\"\"} @ $current_unix_time) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-events\"}\r\n| json\r\n| metadata_namespace = \"$namespace\"\r\n| metadata_name =~ \".*$pod_filter.*\""
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Logs (max 200 lines)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-pod-logs\", _namespace=\"$namespace\"}\r\n| json\r\n| line_format `- {{printf \"%-8.8s\" ._level}} - {{printf \"%-14.14s\" ._namespace}} - {{printf \"%-50.50s\" ._pod}} - {{if .template_parsed}}{{.template_parsed}}{{else if .log}}{{.log}}{{else if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 200
    }
   ]
  },
  { "title": "Network usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Receive bandwith by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_receive_bytes_total{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (pod)\r\n    )[$average]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit bandwith by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_transmit_bytes_total{job=\"cadvisor\", namespace=\"$namespace\", pod=~\".*$pod_filter.*\"}[$__rate_interval])) by (pod)\r\n    )[$average]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}