{
 "title": "Resources (Cluster)",
 "tags": [
  "iiot",
  "resources",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "average",
    "label": "Moving Average",
    "query": "None : 1s, 1m, 5m, 10m, 15m, 30m, 1h, 3h, 6h"
   },
   { "name": "current_unix_time", "query": { "query": "" } },
   { "name": "namespace_filter", "label": "Namespace Filter" },
   {
    "name": "memory_type",
    "label": "Memory Type",
    "query": "Working Set : container_memory_working_set_bytes, RSS : container_memory_rss"
   }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU cores by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\", container!=\"\"}[$__rate_interval])) by (namespace) * 1000\r\n    )[$average]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory by namespace ($memory_type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum({__name__=\"$memory_type\", job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\", container!=\"\"}) by (namespace)\r\n    )[$average]\r\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\", container!=\"\"}[2m] @ $current_unix_time)) by (namespace) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_owner{job=\"kube_state_metrics\", namespace=~\".*$namespace_filter.*\"} @ $current_unix_time) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\", container!=\"\"} @ $current_unix_time) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_namespace_status_phase{job=\"kube_state_metrics\", namespace=~\".*$namespace_filter.*\"} @ $current_unix_time == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{job=\"kube_state_metrics\", condition=\"true\", namespace=~\".*$namespace_filter.*\"}) by (namespace)\r\n+\r\nsum(kube_pod_status_phase{job=\"kube_state_metrics\", phase=\"Succeeded\", namespace=~\".*$namespace_filter.*\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "$current_unix_time\r\n-\r\nmax(kube_namespace_created{job=\"kube_state_metrics\", namespace=~\".*$namespace_filter.*\"}) by (namespace)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_rss{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\", container!=\"\"} @ $current_unix_time) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-events\"}\r\n| json\r\n| metadata_namespace=~\".*$namespace_filter.*\""
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Logs (max 200 lines)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-pod-logs\"}\r\n| json\r\n| line_format `- {{printf \"%-8.8s\" ._level}} - {{printf \"%-14.14s\" ._namespace}} - {{printf \"%-50.50s\" ._pod}} - {{if .template_parsed}}{{.template_parsed}}{{else if .log}}{{.log}}{{else if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 200
    }
   ]
  },
  { "title": "Network usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Receive Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_receive_bytes_total{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\"}[$__rate_interval])) by (namespace)\r\n    )[$average]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        sum(irate(container_network_transmit_bytes_total{job=\"cadvisor\", namespace=~\".*$namespace_filter.*\", pod!=\"\"}[$__rate_interval])) by (namespace)\r\n    )[$average]\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}