{
 "title": "System",
 "tags": [
  "iiot",
  "div"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interface_speeds",
    "query": {
     "query": "query_result((max_over_time(node_network_speed_bytes{job=\"node_exporter\"}[$__range]) * 8 / 1000000000))"
    }
   },
   {
    "name": "average",
    "label": "Moving Average",
    "query": "None : 1s, 1m, 5m, 10m, 15m, 30m, 1h, 3h, 6h"
   },
   { "name": "process_topk", "label": "Process Topk", "query": "20" },
   {
    "name": "highest_cpu_processes",
    "query": {
     "query": "query_result(topk($process_topk, increase(pid_process_cpu_seconds_total{job=\"process_exporter\"}[$__range])))"
    }
   },
   {
    "name": "highest_memory_processes",
    "query": {
     "query": "query_result(topk($process_topk, avg_over_time(pid_process_memory_usage{job=\"process_exporter\"}[$__range])))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage (system/user)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n       (\r\n            max by (cpu) (\r\n                irate(\r\n                    node_cpu_seconds_total{job=\"aggregated_metric_exporter\"}[$__rate_interval]\r\n                )\r\n            )\r\n        ) \r\n    )[$average]\r\n)",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory usages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        max (node_memory_MemTotal_bytes{job=\"node_exporter\"})\r\n        -\r\n        max (node_memory_MemAvailable_bytes{job=\"node_exporter\"})\r\n    )[$average]\r\n)",
     "legendFormat": "Used memory"
    },
    {
     "expr": "max (node_memory_MemTotal_bytes{job=\"node_exporter\"})"
    },
    {
     "expr": "max (node_memory_MemTotal_bytes{job=\"node_exporter\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Disk usages",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        max(node_filesystem_size_bytes{job=\"node_exporter\", mountpoint=\"/var\"})\r\n        -\r\n        max(node_filesystem_avail_bytes{job=\"node_exporter\", mountpoint=\"/var\"})\r\n    )[$average]\r\n)",
     "legendFormat": "Used disk space {{device}}"
    },
    {
     "expr": "max(node_filesystem_size_bytes{job=\"node_exporter\"})"
    },
    {
     "expr": "max(node_filesystem_size_bytes{job=\"node_exporter\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU usage (highest $process_topk)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        max(irate(pid_process_cpu_seconds_total{job=\"process_exporter\", pid=~\"$highest_cpu_processes\"}[$__rate_interval])) by (pid, command) * 1000\r\n    )[$average]\r\n)",
     "legendFormat": "{{pid}} ({{command}})"
    }
   ]
  },
  {
   "title": "Memory usage (highest 20)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        max(pid_process_memory_usage{job=\"process_exporter\", pid=~\"$highest_memory_processes\"}) by (pid, command)\r\n    )[$average]\r\n)",
     "legendFormat": "{{pid}} ({{command}})"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(pid_process_cpu_seconds_total{job=\"process_exporter\"}[$__rate_interval])) by (pid, command) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pid_process_memory_usage{job=\"process_exporter\"}) by (pid, command)",
     "legendFormat": "__auto"
    },
    {
     "expr": "pid_process_info{job=\"process_exporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(pid_process_cpu_seconds_total{job=\"process_exporter\"}[$__range]) / $__range_s * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(pid_process_memory_usage{job=\"process_exporter\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network usage ($interface_speeds Gbit/s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "repeat": "interface_speeds"
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n    (\r\n        max by (device) (node_network_speed_bytes{job=\"node_exporter\"} * 8 / 1000000000 == ${interface_speeds:raw})\r\n        *\r\n        on(device)\r\n        group_left()\r\n        max by (device) (\r\n            irate(node_network_receive_bytes_total{job=\"node_exporter\"}[$__rate_interval]) * 8  # Convert from MB to Mbit\r\n        )\r\n        /\r\n        ${interface_speeds:raw}\r\n    )[$average]\r\n)",
     "legendFormat": "receiving ({{device}})"
    },
    {
     "expr": "avg_over_time(\r\n    (\r\n        max by (device) (node_network_speed_bytes{job=\"node_exporter\"} * 8 / 1000000000 == ${interface_speeds:raw})\r\n        *\r\n        on(device)\r\n        group_left()\r\n        max by (device) (\r\n            irate(node_network_transmit_bytes_total{job=\"node_exporter\"}[$__rate_interval]) * 8  # Convert from MB to Mbit\r\n        )\r\n        /\r\n        ${interface_speeds:raw}\r\n    )[$average]\r\n)",
     "legendFormat": "transmitting ({{device}})"
    },
    {
     "expr": "${interface_speeds:raw} * 1000000000",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}