{
 "title": "Talos Logs",
 "tags": [
  "iiot",
  "div"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "columns",
    "label": "Columns",
    "query": "Level : level, Service : service, None : none"
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": "critical, error, warning, info, debug, trace, unknown"
   },
   { "name": "line_filter", "label": "Line filter" },
   { "name": "extra_filter", "label": "Extra filter" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logs (max 500 lines)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{_job=\"fluent-bit-talos-logs\", _service=~\"$service\", _level=~\"$level\"}\r\n|= \"$line_filter\"\r\n| json\r\n| line_format `{{if count \"$columns\" \"level\"}}- {{printf \"%-8.8s\" ._level}} {{end}}{{if count \"$columns\" \"service\"}}- {{printf \"%-14.14s\" ._service}} {{end}}- {{if .msg}}{{.msg}}{{else}}{{__line__}}{{end}}`\r\n| drop _job",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "Logs per level",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-talos-logs\", _service=~\"$service\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{_level}}"
    }
   ]
  },
  {
   "title": "Logs per service",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-talos-logs\", _service=~\"$service\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_service)",
     "legendFormat": "{{_service}}"
    }
   ]
  },
  { "title": "Additional statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(\r\n    count_over_time(\r\n        {_job=\"fluent-bit-talos-logs\", _service=~\"$service\", _level=~\"$level\"}\r\n        |= \"$line_filter\"\r\n        | json\r\n        [$__interval]\r\n    )\r\n) by (_level)",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}